spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/interior_company?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: root
  thymeleaf:
    cache: false
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    # 连接超时时间（ms)
    timeout: 5000
    # 高版本springboot中使用jedis或者lettuce
    jedis:
      pool:
        # 连接池最大连接数（负值表示无限制）
        max-active: 8
        # 连接池最大阻塞等待时间（负值无限制)
        max-wait: 5000ms
        # 最大空闲链接数
        max-idle: 8
        # 最小空闲链接数
        min-idle: 0
mybatis:
  mapper-locations: classpath:mappers/*.xml